# -*- coding: utf-8 -*-
"""Copy of Copy of Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P6S3mhaanvzlcAjytpMmusZq1AmGRv6Q
"""

print("\t\t\t CHILLS")
print("WARNING!!! Enter at your own risk")
print("you will have to choose paths,if you go in the correct lane you will reach home.otherwise there's a MONSTER waiting for YOU!")
ans = input("would you still consider tp play thIS game? ('yes' or 'no'): ")


if ans.lower() == 'yes':
  ans = input("which way do you want to go first? ('north'/'east'/'west'/'south'): ")
  if ans == 'north' or ans == 'west':
     
    while True:
      number = int(input("select a lane from - 7, 3, 9, 1, 5: "))
      if number == 9:
        print("\n THE MONSTER KILLED YOU!!")
        break
      elif number == 5:
        print("\n you're trapped in the forest, you chose the wrong lane!")
        break
      elif number == 7:
        print("Brave move!, but you,re trapped!")
        break
      elif number == 3:
        print("you've safely reached home congratulations!")
      elif number == 1:
        print("you fought with the monster and reached home..congratulations!!")
        break
      else: print("7, 3, 9, 1, 5 are the only numbers allowed.")

  if ans == "east" or "south":
    while True:
      number = int(input("select a lane from - 2, 8, 6, 4: "))
      if number == 2: 
         print("you destroyed the monster and reached home happily! hurrah!!")
         break
      elif number == 8:
        print("you got killed by the monster brutally")
        break
      elif number == 6:
        print("the monster ripped your heart into two and killed you!")
        break
      elif number == 4:
        print("an agel protected you from the monster and helped you to reach home!")
      else: print("2, 8, 6, 4 are the only numbers allowed.")
      continue 
      c = input("\nDo you want to play again? ('yes' or 'no'): ")